apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb
  template:
    metadata:
      labels:
        app: lb
    spec:
      containers:
      - name: nginx-lb
        image: <dockerhubusername>/nginx-lb:latest
        ports:
        - containerPort: 80
